name: Deploy to servers flow
on:
  check_suite:
    types: [completed]
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: tarrynn/elixir_docker:latest

    steps:
    - name: Start Postgresql
      run: |
        echo "Deploying to servers only if previous checks passed"
