name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: tarrynn/elixir_docker:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo -i -u ubuntu bash -c "/usr/lib/postgresql/9.6/bin/pg_ctl -o \"-p 5432\" -D /var/lib/postgresql/9.6/main -l logfile start"
        /usr/lib/postgresql/9.6/bin/pg_isready --host=docker --port=5432 --username=postgres
        echo "127.0.0.1 docker" >> /etc/hosts
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        cd ./assets && npm install
        cd ..
        npm run deploy --prefix ./assets
        MIX_ENV=test mix ecto.setup
    - name: Run Tests
      run: mix test
